# Generated by Django 6.0.3 on 2026-04-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prophecies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='title',
            field=models.CharField(default='Untitled Fulfillment', max_length=255),
            preserve_default=False,
        ),
    ]
