# Generated by Django 6.0.3 on 2026-06-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_title', models.CharField(max_length=255)),
                ('before_description', models.TextField(blank=True, null=True)),
                ('before_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('before_media', models.FileField(upload_to='testimonies/before/')),
                ('after_title', models.CharField(max_length=255)),
                ('after_description', models.TextField(blank=True, null=True)),
                ('after_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('after_media', models.FileField(upload_to='testimonies/after/')),
                ('is_downloadable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
