# Generated by Django 6.0.3 on 2026-04-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='after_description',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='before_description',
        ),
    ]
