# Generated by Django 6.0.3 on 2026-04-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_rename_short_description_testimony_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='title',
            new_name='after_title',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='description',
        ),
        migrations.AddField(
            model_name='testimony',
            name='after_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='before_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimony',
            name='before_title',
            field=models.CharField(default='Pending Before Title', max_length=255),
            preserve_default=False,
        ),
    ]
