# Generated by Django 6.0.3 on 2026-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_url', models.URLField()),
                ('max_duration_minutes', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('recorded', 'Recorded'), ('downloaded', 'Downloaded'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('size_mb', models.FloatField(blank=True, null=True)),
                ('download_attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
