# Generated by Django 6.0.3 on 2026-04-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiosettings',
            name='max_duration_minutes',
            field=models.IntegerField(default=90),
        ),
    ]
